/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exfinal;

import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Fortress of Solitude
 */
public class ExFinalForm extends javax.swing.JFrame {

    public ArrayList<Integer> numerosGenerados = new ArrayList<>(); 
    public int numeroAciertos = 0;
    public double montoGanado = 0;
    
    /**
     * Creates new form ExFinalForm
     */
    public ExFinalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoteria = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        txtNumero01 = new javax.swing.JTextField();
        txtNumero02 = new javax.swing.JTextField();
        txtNumero03 = new javax.swing.JTextField();
        txtNumero04 = new javax.swing.JTextField();
        txtNumero05 = new javax.swing.JTextField();
        btnRealizarJugada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblLoteria.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblLoteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoteria.setText("Loteria");

        btnGenerar.setText("Generar Numeros ");

        txtNumero01.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumero01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero01.setText("00");

        txtNumero02.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumero02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero02.setText("00");

        txtNumero03.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumero03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero03.setText("00");

        txtNumero04.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumero04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero04.setText("00");
        txtNumero04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero04ActionPerformed(evt);
            }
        });

        txtNumero05.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumero05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero05.setText("00");

        btnRealizarJugada.setText("REALIZAR JUGADA");
        btnRealizarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarJugadaActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblLoteria)
                        .addGap(319, 319, 319)
                        .addComponent(btnGenerar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                        .addComponent(btnRealizarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtNumero01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtNumero02, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtNumero03, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtNumero04, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtNumero05, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoteria)
                    .addComponent(btnGenerar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNumero01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero02, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero03, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero04, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero05, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRealizarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumero04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero04ActionPerformed

    private void btnRealizarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarJugadaActionPerformed
      
        
    }//GEN-LAST:event_btnRealizarJugadaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExFinalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRealizarJugada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoteria;
    private javax.swing.JTextField txtNumero01;
    private javax.swing.JTextField txtNumero02;
    private javax.swing.JTextField txtNumero03;
    private javax.swing.JTextField txtNumero04;
    private javax.swing.JTextField txtNumero05;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
